// The Rust↔TS payload shapes (AppConfig, TabSession, FileMetadata,
// ColorMode, NoteWithMetadata) are generated from the `#[derive(TS)]`
// structs in `src-tauri/src/storage.rs` — see `./generated/tauri-types.ts`
// (regenerated by `cd src-tauri && cargo test`, CI-gated). Re-exported
// here so the rest of the app keeps a single `./types` import.
export type {
  AppConfig,
  ColorMode,
  FileMetadata,
  ImportMode,
  ImportResult,
  NoteWithMetadata,
  TabSession,
  ThemeMode,
} from "./generated/tauri-types";

// --- Frontend-only shapes (no Rust counterpart) -----------------------

export interface NoteTab {
  id: string;
  filename: string;
  isScratchpad: boolean;
  content: string;
}

export interface ActionSnapshotItem {
  id: string;
  /** Present when the source file is already open as a tab; absent for
   * "All Files" mode results whose file isn't open yet. */
  tabId?: string;
  filename: string;
  lineIdx: number;
  line: string;
  header: string;
}

export interface HistoryItem {
  filename: string;
  lineIdx: number;
  /** The full source line (for the "From" context preview and jump). */
  line: string;
  /** #41: the single action this row represents — the leading action with
   * its text taken up to the first ` => `, or a follow-up's inner action
   * (`# text`) / plain follow-up (`=> text`). One source line can produce
   * more than one `HistoryItem` when it carries both. This is what the
   * row renders and what Shift+Enter inserts. */
  action: string;
  date: string;
}

/** #27/#33: the body of a recurring section as it stood at its previous
 * occurrence (the last dated note before the one Section History was
 * opened from) — a "what did we cover last time" snapshot, glyph-rendered
 * read-only in its own pane, distinct from the deduped all-dates
 * aggregate in the list below it. */
export interface PreviousSectionOccurrence {
  filename: string;
  date: string;
  /** Section body lines, from just after the setext underline to just
   * before the next section header (trailing blank lines dropped). */
  lines: string[];
  /** 0-based index of the first body line in the source file. */
  startLineIdx: number;
}

export interface SearchResultItem {
  /** Present when the source file is already open as a tab; absent for
   * "All Files" mode results whose file isn't open yet. */
  tabId?: string;
  tabFilename: string;
  lineIdx: number;
  line: string;
}
