// The Rust↔TS payload shapes (AppConfig, TabSession, FileMetadata,
// ColorMode, NoteWithMetadata) are generated from the `#[derive(TS)]`
// structs in `src-tauri/src/storage.rs` — see `./generated/tauri-types.ts`
// (regenerated by `cd src-tauri && cargo test`, CI-gated). Re-exported
// here so the rest of the app keeps a single `./types` import.
export type { AppConfig, ColorMode, FileMetadata, NoteWithMetadata, TabSession } from "./generated/tauri-types";

// --- Frontend-only shapes (no Rust counterpart) -----------------------

export interface NoteTab {
  id: string;
  filename: string;
  isScratchpad: boolean;
  content: string;
}

export interface ActionSnapshotItem {
  id: string;
  /** Present when the source file is already open as a tab; absent for
   * "All Files" mode results whose file isn't open yet. */
  tabId?: string;
  filename: string;
  lineIdx: number;
  line: string;
  header: string;
}

export interface HistoryItem {
  filename: string;
  lineIdx: number;
  line: string;
  date: string;
}

/** #27: the verbatim body of a recurring section as it stood at its most
 * recent occurrence before the note Section History was opened from — a
 * literal "what did we cover last time" snapshot, shown as its own panel
 * in the drawer, distinct from the glyph-stripped, deduped, all-dates
 * aggregate in the list. */
export interface LastSectionOccurrence {
  filename: string;
  date: string;
  /** Section body, verbatim, from just after the setext underline to
   * just before the next section header (trailing blank lines dropped). */
  lines: string[];
  /** 0-based index of the first body line in the source file. */
  startLineIdx: number;
}

export interface SearchResultItem {
  /** Present when the source file is already open as a tab; absent for
   * "All Files" mode results whose file isn't open yet. */
  tabId?: string;
  tabFilename: string;
  lineIdx: number;
  line: string;
}
