// The Rust↔TS payload shapes (AppConfig, TabSession, FileMetadata,
// ColorMode, NoteWithMetadata) are generated from the `#[derive(TS)]`
// structs in `src-tauri/src/storage.rs` — see `./generated/tauri-types.ts`
// (regenerated by `cd src-tauri && cargo test`, CI-gated). Re-exported
// here so the rest of the app keeps a single `./types` import.
export type {
  AppConfig,
  AppError,
  ColorMode,
  FileMetadata,
  ImportMode,
  ImportResult,
  NoteWithMetadata,
  OneDriveAccount,
  OneDriveAdvancedConfig,
  FolderSwitchBlocked,
  FolderSwitchResult,
  LanguageMode,
  OneDriveFolderConfig,
  OneDriveFolderItem,
  OneDriveLoginResult,
  OneDriveSyncResult,
  SyncConflict,
  SyncHealth,
  SyncStatus,
  TabSession,
  ThemeMode,
} from "./generated/tauri-types";

// --- Frontend-only shapes (no Rust counterpart) -----------------------

export interface NoteTab {
  id: string;
  filename: string;
  isScratchpad: boolean;
  content: string;
}

export interface ActionSnapshotItem {
  id: string;
  /** Present when the source file is already open as a tab; absent for
   * "All Files" mode results whose file isn't open yet. */
  tabId?: string;
  filename: string;
  lineIdx: number;
  line: string;
  header: string;
}

/** One dated note's rendition of a recurring section — every file that has
 * the section at all becomes one of these, whether or not it has any
 * content, so Section History's occurrence list can show every occurrence,
 * past or future, browsable the same way (2026-09-24 redesign: browsing full
 * occurrences replaced the earlier flat, deduped action list). */
export interface SectionOccurrence {
  filename: string;
  date: string;
  /** Full section body, from just after the setext underline to just
   * before the next section header (trailing blank lines dropped) — used
   * to glyph-render the occurrence in full, scrollable, in the drawer's
   * preview pane. */
  lines: string[];
  /** 0-based index of the first body line in the source file. */
  startLineIdx: number;
}

/** Where a Section History "take it over" can land — computed once when
 * the drawer opens, from the opened-from tab's own date (2026-09-24
 * redesign, docs/design/section-history-browse-and-carry-forward-roadmap.md).
 * `"here"` when the opened-from tab is today, in the future, or a
 * scratchpad (no date to compare); otherwise `"today"` and, if one exists,
 * `"next"` — never both `"here"` and `"today"/"next"` at once. */
export type HistoryDestination =
  | { kind: "here"; tabId: string; label: string }
  | { kind: "today"; date: string; headerText: string; label: string }
  | { kind: "next"; date: string; headerText: string; label: string };

export interface SearchResultItem {
  /** Present when the source file is already open as a tab; absent for
   * "All Files" mode results whose file isn't open yet. */
  tabId?: string;
  tabFilename: string;
  lineIdx: number;
  line: string;
  /** One line of context before the matched line, if within document bounds. */
  contextBefore?: string;
  /** One line of context after the matched line, if within document bounds. */
  contextAfter?: string;
}
