name: Translation issue
description: Report a translation problem or suggest a better translation
labels: ["translation"]
body:
  - type: dropdown
    id: language
    attributes:
      label: Language
      options:
        - Nederlands
        - Deutsch
        - Français
        - Polski
        - Español
        - Italiano
  - type: input
    id: where
    attributes:
      label: "Where in the app?"
  - type: input
    id: now
    attributes:
      label: "Current text"
    validations:
      required: true
  - type: input
    id: better
    attributes:
      label: "Better text"
    validations:
      required: true
